name: C++ Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Build hello.cpp
        run: g++ hello.cpp -o hello

      - name: Run hello
        run: ./hello
