name: C++ Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Build hello.cpp
        run: g++ hello.cpp -o hello

      - name: Create build directory
        run: mkdir -p build

      - name: Copy executable to build directory
        run: cp hello build/

      - name: List build directory contents
        run: ls -l build

      - name: Upload build directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/
